AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  stepfunctions-enrichment

  A sample SAM application that illustrates a data enrichment use case for AWS Step Functions.

Globals:
  Function:
    Runtime: python3.9
    Handler: app.lambda_handler
    Timeout: 10
    Tags:
      AssociatedApp: enrichment-orchestrator-demo
    Architectures:
      - arm64

Resources:

  SfnEnrichmentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/vendedlogs/states/enrichment-orchestrator
      RetentionInDays: 14

  SfnEnrichment:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/enrichment-orchestrator.asl.json
      DefinitionSubstitutions:
        GetFullOrderDetailsFunctionArn: !GetAtt GetFullOrderDetails.Arn
        GetSystemXFunctionArn: !GetAtt GetSystemX.Arn
        GetSystemYFunctionArn: !GetAtt GetSystemY.Arn
        MakePDFFunctionArn: !GetAtt MakePDF.Arn
      Tags:
        AssociatedApp: enrichment-orchestrator-demo
      Tracing:
        Enabled: True
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SfnEnrichmentLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Events:
        DemoEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - demo.pos
              detail:
                action:
                  - create-receipt
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetFullOrderDetails
        - LambdaInvokePolicy:
            FunctionName: !Ref GetSystemX
        - LambdaInvokePolicy:
            FunctionName: !Ref GetSystemY
        - LambdaInvokePolicy:
            FunctionName: !Ref MakePDF
        - Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Action:
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "logs:CreateLogDelivery"
                - "logs:GetLogDelivery"
                - "logs:UpdateLogDelivery"
                - "logs:DeleteLogDelivery"
                - "logs:ListLogDeliveries"
                - "logs:PutResourcePolicy"
                - "logs:DescribeResourcePolicies"
                - "logs:DescribeLogGroups"
              Resource:
                - "*"

  GetFullOrderDetails:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_order_details/

  GetSystemX:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_system_x/

  GetSystemY:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_system_y/

  MakePDF:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/make_pdf/


Outputs:
  StepFunctionsStateMachineArn:
    Description: "State machine ARN"
    Value: !Ref SfnEnrichment
